export { config, defaultConfig, getConfig } from './config'
export { installGitHooks, uninstallGitHooks } from './hooks'
export { lintCommitMessage } from './lint'
export { parseCommitMessage } from './parser'
export { rules } from './rules'
export * from './types'
export { readCommitMessageFromFile } from './utils'
